// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxVueJKOEh7Bk-8H9zBuY6gcPex3hstyE',
    appId: '1:569231581248:web:42aa2f609b7de14685ffa5',
    messagingSenderId: '569231581248',
    projectId: 'fir-study-69fcb',
    authDomain: 'fir-study-69fcb.firebaseapp.com',
    databaseURL: 'https://fir-study-69fcb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-study-69fcb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANut6-Rb1LKz5pmywKyE4j5H8wz5GSMfY',
    appId: '1:569231581248:android:20cfd42a6e1c430285ffa5',
    messagingSenderId: '569231581248',
    projectId: 'fir-study-69fcb',
    databaseURL: 'https://fir-study-69fcb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-study-69fcb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfiC-D8fR5svrLcBgkgyg7SmPx3EZh6co',
    appId: '1:569231581248:ios:d3347670315f90e585ffa5',
    messagingSenderId: '569231581248',
    projectId: 'fir-study-69fcb',
    databaseURL: 'https://fir-study-69fcb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-study-69fcb.firebasestorage.app',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfiC-D8fR5svrLcBgkgyg7SmPx3EZh6co',
    appId: '1:569231581248:ios:d3347670315f90e585ffa5',
    messagingSenderId: '569231581248',
    projectId: 'fir-study-69fcb',
    databaseURL: 'https://fir-study-69fcb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-study-69fcb.firebasestorage.app',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxVueJKOEh7Bk-8H9zBuY6gcPex3hstyE',
    appId: '1:569231581248:web:8fef1321f685b51885ffa5',
    messagingSenderId: '569231581248',
    projectId: 'fir-study-69fcb',
    authDomain: 'fir-study-69fcb.firebaseapp.com',
    databaseURL: 'https://fir-study-69fcb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-study-69fcb.firebasestorage.app',
  );
}
